### PR TITLE
Fix search page crash

### LINKED ISSUE #529: Page crash when switching between course/professor popup results
Search up any query, click on one result, then click on another and the page will crash

### PR DESCRIPTION
**Pull request by js0mmer**
## Description

* Updated conditions in GradeDist to make sure gradeDistData is not undefined
* Removed use of non-null assertions in state initializations for better type safety

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

(optional)

- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #529

### CODE REVIEW

File: site/src/component/GradeDist/GradeDist.tsx [hunk 1]
```diff
@@ -156,7 +156,7 @@ const GradeDist: FC<GradeDistProps> = (props) => {
 
   // update list of quarters when new professor/course is chosen
   useEffect(() => {
-    if ((currentProf || currentCourse) && gradeDistData.length !== 0) {
+    if ((currentProf || currentCourse) && gradeDistData && gradeDistData.length !== 0) {
```
Comment (Awesome-E) [inline site/src/component/GradeDist/GradeDist.tsx:159]: If you want it to be more concise, you can do:
```suggestion
    if ((currentProf || currentCourse) && gradeDistData?.length) {
```

That's readable to me, but I may be used to it more than others. Your call.

**Review by Awesome-E — APPROVED** [review]

**Comment by Awesome-E** [comment]
LGTM!
