### PR TITLE
Fixed Recent Offerings to only be rendered if there are any offerings

### LINKED ISSUE #823: Professor pages should not display "Recent Offerings"
**Describe the bug**
If you go to a professor page, there's an unnecessary "Recent Offerings" header on the left side overview.

**To Reproduce**
1. Go to any professor page

**Expected Behavior**
"Recent Offerings" should not be there.

**Actual Behavior**

Image

**Additional context**
Eventually, it would be nice to have a "Recent Courses" table. However, that's out of the scope of this issue and we should just remove the visual bug for now.

### PR DESCRIPTION
**Pull request by anonymous-himalayas**
## Description

Added checks for rendering Recent Offerings only if there are any term properties.

## Test Plan

Go to any professor and Recent Offerings should no longer show

## Issues

Closes #823

### CODE REVIEW

**Review by fiveminus1 — CHANGES_REQUESTED** [review]
Hey Hamil, thanks for the contribution!

You shouldn't have to touch the `parseOfferings` function for this - that's only internally used by the `RecentOfferingsTable`. The issue is that `<h4>Recent Offerings</h4>` is displayed despite there being no `terms` in the props for a Professor page (more generally, if no terms are found for a given page, professor or course, then the header shouldn't be displayed).

File: site/src/component/SideInfo/SideInfo.tsx [hunk 1]
```diff
@@ -159,8 +159,12 @@ const SideInfo: FC<SideInfoProps> = (props) => {
           </div>
         </div>
 
-        <h4>Recent Offerings</h4>
-        {props.terms && <RecentOfferingsTable terms={props.terms} size="wide" />}
+        {props.terms && props.terms.length > 0 && (
```
Comment (fiveminus1) [inline site/src/component/SideInfo/SideInfo.tsx]: Checking the length of `props.terms` is redundant since the `props.terms &&` condition already does the same

**Review by fiveminus1 — APPROVED** [review]
money moves

**Review by Awesome-E — APPROVED** [review]
💰🦐
